# prometheus/prometheus.yml
global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'whosper'
    static_configs:
      - targets: ['backend:8000']
    metrics_path: '/metrics'